### ISSUE TITLE
kamu sql issue

### ISSUE THREAD

**Issue by rezar362** [kamu-data/kamu-cli#235]
Here is the error I see when I try to run sql in kamu on a Mac device:
(base) jovyan@a0a32dfc1454:~/01 - Kamu Basics (COVID-19 example)$ kamu sql
Error:
  0: Internal error
  1: Failed pulling image: ghcr.io/kamu-data/engine-spark:0.19.1-spark_3.1.2
  2: Process exited with code 125
- Command { std: "podman" "pull" "ghcr.io/kamu-data/engine-spark:0.19.1-spark_3.1.2", kill_on_drop: false }
- STDOUT:
- STDERR: time="2023-09-15T22:51:21Z" level=warning msg="\"/\" is not a shared mount, this could causeissues or missing mounts with rootless containers"
cannot clone: Invalid argument
Error: cannot re-exec process

Help us by reporting this problem at https://github.com/kamu-data/kamu-cli/issues

**Comment by sergiimk** [comment]
Hi @rezar362 thanks for reporting this issue.

This seems like a `podman` configuration problem.

Have you tried to run `podman pull "ghcr.io/kamu-data/engine-spark:0.19.1-spark_3.1.2"` directly or pulling any other image and see if it still fails?

I know on Mac podman runs under a VM (`podman machine`) so there might be some quirks around shared storage between this VM and the host OS.

We run our tests on Mac VMs but unfortunately none of us have actual Macs to tests this on.

**Comment by rezar362** [comment]
Thanks a lot for checking this issue.
I tried to run this on WSL2, and Linux also the online demo version with Mac, Linux and Windows. I have the same issue that I can not run kamu sql, or kamu notebook.

**Comment by rezar362** [comment]
I can pull that imahe and works, the problem is even with the online demo, I want to recommend this for an organization for analytic reporting purpose, I appreciate if you can help to fix it:   

docker  pull ghcr.io/kamu-data/engine-spark:0.19.1-spark_3.1.2
0.19.1-spark_3.1.2: Pulling from kamu-data/engine-spark
2e4c6c15aa52: Pull complete
cfd109e85a57: Pull complete
81a64fdbdba4: Pull complete
72d23c87178d: Pull complete
462f67a7fc33: Pull complete
ea706685fa63: Pull complete
afc0aa3777c7: Pull complete
f3ec35144ba7: Pull complete
0ebe376e4821: Pull complete
8d94fdbbb9a8: Pull complete
0d8a2a51dfbe: Pull complete
d3b8d16b4e84: Pull complete
40c8cfd683a7: Pull complete
3407010eaefc: Pull complete
3fbb97a8b30b: Pull complete
f2ec93f4a454: Pull complete
acc7d9a2aab9: Pull complete
ae80139f878a: Pull complete
8be64b481cbc: Pull complete
d5f75fdc19ec: Pull complete
Digest: sha256:a998a5d2a6d730922eb7b88c356ae54a0179e88e162cbef21f78b857970c3497
Status: Downloaded newer image for ghcr.io/kamu-data/engine-spark:0.19.1-spark_3.1.2
ghcr.io/kamu-data/engine-spark:0.19.1-spark_3.1.2

What's Next?
  1. Sign in to your Docker account → docker login
  2. View a summary of image vulnerabilities and recommendations → docker scout quickview ghcr.io/kamu-data/engine-spark:0.19.1-spark_3.1.2

**Comment by sergiimk** [comment]
Please not that we have since added a new SQL console based on DataFusion engine which is extremely fast compared to Spark and does not require a container, so it should work much better on Mac.
