### ISSUE TITLE
Flow System (BE)

### ISSUE THREAD

**Issue by zaychenko-sergei** [kamu-data/kamu-cli#274]
Represents Backend-side work that should feed frontend [Task System FE](https://github.com/kamu-data/kamu-web-ui/issues/170) epic.

Tasks:
 - https://github.com/kamu-data/kamu-cli/issues/275
 - https://github.com/kamu-data/kamu-cli/issues/276
 - https://github.com/kamu-data/kamu-cli/issues/277 (needs to be reconsidered)
 - https://github.com/kamu-data/kamu-cli/issues/278
 - https://github.com/kamu-data/kamu-cli/issues/279
 - https://github.com/kamu-data/kamu-cli/issues/280
 - https://github.com/kamu-data/kamu-cli/issues/281
 - https://github.com/kamu-data/kamu-cli/issues/282
 - https://github.com/kamu-data/kamu-cli/issues/283
 - https://github.com/kamu-data/kamu-cli/issues/284
 - https://github.com/kamu-data/kamu-cli/issues/285
 - https://github.com/kamu-data/kamu-cli/issues/286
 - https://github.com/kamu-data/kamu-cli/issues/287
 - https://github.com/kamu-data/kamu-cli/issues/396
 - https://github.com/kamu-data/kamu-cli/issues/397
 - https://github.com/kamu-data/kamu-cli/issues/398
 - https://github.com/kamu-data/kamu-cli/issues/399
 - https://github.com/kamu-data/kamu-cli/issues/400
 - https://github.com/kamu-data/kamu-cli/issues/401
 - https://github.com/kamu-data/kamu-cli/issues/419

**Comment by sergiimk** [comment]
I have created a combined `Product` swimlane in our roadmap and moved the tracking of backend tasks into https://github.com/kamu-data/kamu-web-ui/issues/170
