### ISSUE TITLE
Misleading messages in 'kamu notebook'

### ISSUE THREAD

**Issue by LinuxUser404** [kamu-data/kamu-cli#3]
Running kamu notebook produces rather misleading messages for the users:
1) [jupyter] [W 19:50:36.294 NotebookApp] No web browser found: could not locate runnable browser.
2) [jupyter] [I 19:50:36.289 NotebookApp] http://(kamu-jupyter or 127.0.0.1):80/?token=9101880d8cd3f305cb81df5251ae7edb965b27bc68e15b73
3) [jupyter]     To access the notebook, open this file in a browser:
[jupyter]         file:///root/.local/share/jupyter/runtime/nbserver-1-open.html

It should let the user know what URL to use. That is something like:
[INFO] Opening in browser: http://localhost:32768/?token=9101880d8cd3f305cb81df5251ae7edb965b27bc68e15b73

Where '32768' is the port mapped by docker(can be checked with 'docker ps -a')

**Comment by sergiimk** [comment]
Fixed in new Rust UI
