### ISSUE TITLE
Introduce clippy linting

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-cli#332]
## Requirements

Far too long we have been ignoring this. Now that there are more people are working on this project it's time to stricten-up our standards.

- Add CI step for `clippy`
- Assess how it affects the build performance
- Propose a gradual path to introduce it over time

### Game plan
- [x] `1st phase`
  - [x] Codegen area
    - [x] Update codegen scripts https://github.com/open-data-fabric/open-data-fabric/pull/76
    - [x] Configure ignored files (`*_generated.rs`) ~~OR fix it right after generation~~ https://github.com/open-data-fabric/open-data-fabric/pull/76
      - Context: https://github.com/kamu-data/kamu-cli/pull/446#discussion_r1453216369
  - [x] Fix the current code with auto-fix `clippy` functional
    - [x] https://github.com/kamu-data/kamu-cli/pull/437
    - [x] https://github.com/kamu-data/kamu-cli/pull/439
  - [x] Fix manually rest warnings https://github.com/kamu-data/kamu-cli/pull/446
    - [x] https://github.com/kamu-data/kamu-cli/pull/447
- [x] Waiting for the merge https://github.com/kamu-data/kamu-cli/pull/407
- [ ] `2nd phase`
  - [x] `[CI]` Activate failing for the brand-new CI step if warnings present
  - [x] `[CI]` Add CI step for `cargo clippy` w/o failing (to measure times, +2m 55s to "Lint / Formatting" step) https://github.com/kamu-data/kamu-cli/pull/453
  - [x] Activate `pedantic` ruleset
    - [x] Automatic fixes
      - [x] https://github.com/kamu-data/kamu-cli/pull/460
      - [x] https://github.com/open-data-fabric/open-data-fabric/pull/79
    - [x] Manual fixes
      - [x] https://github.com/kamu-data/kamu-cli/pull/464
      - [x] https://github.com/kamu-data/kamu-cli/pull/466
    - [x] `[CI]` Enable pedantic ruleset 
  - [x] Discuss problematic/questionable `clippy` rules
  - [x] Reactivate disabled `clippy` rules
    - [x] https://github.com/kamu-data/kamu-cli/pull/473
    - [x] https://github.com/kamu-data/kamu-cli/pull/489
    - [x] https://github.com/kamu-data/kamu-cli/pull/491
  - [x] Aside activities
    - [x] Update `DEVELOPER.md` and `make lint`
    - [x] VSCode `clippy` integration (document that)
  - [ ] `[CI]` Investigate cache for `clippy`

**Comment by s373r** [comment]
@zaychenko-sergei @sergiimk , please take a look at the proposed implementation plan
