### ISSUE TITLE
Support wildcard references in dataset operations

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-cli#336]
Sometimes one really wants to pull a group of datasets at once and using a wildcard would be a nice way to do it.

```sh
kamu pull net.example.*
```

Considerations:
- Design how glob semantics will work
- Consider how asterisk will interact with shell expansions
- Implement a special `DatasetWildcard` type (similar to `DatasetRef`) and a resolution mechanism

**Comment by sergiimk** [comment]
This ticket was in "Done" column on the board but still open - please review the current status @rmn-boiko

**Comment by rmn-boiko** [comment]
I created a separate issue for the next implementation steps https://github.com/kamu-data/kamu-cli/issues/472.
