### ISSUE TITLE
kamu-cli help sql 

### ISSUE THREAD

**Issue by JvD007** [kamu-data/kamu-cli#36]
**_Kamu-cli sql -h_** gives me to following example:

-  kamu sql -c 'SELECT * FROM org.example.data LIMIT 10' -o csv

When I run my command 

- kamu-cli sql -c 'select * from amersfoort.opendata limit 10'

I got the following error:
Error: Error running query: org.apache.spark.sql.AnalysisException: Table or view not found: amersfoort.opendata; line 1 pos 14;
'GlobalLimit 10
+- 'LocalLimit 10
   +- 'Project [*]
      +- 'UnresolvedRelation [amersfoort, opendata] (state=,code=0)

I think the command must look like this, where **'** is **`** in the command below

- **kamu-cli sql -c 'select * from 'amersfoort.opendata' limit 10'**

Then it works, maybe a change for in the help of kamu-cli.

PS: In the help you are using kamu as command, but we use kamu-cli. Bit confusing.

**Comment by sergiimk** [comment]
Thanks Jaco, I've added the missing backticks to the SQL command example.

> PS: In the help you are using kamu as command, but we use kamu-cli. Bit confusing.

I've also update the release scripts to package the executable as `kamu` instead of `kamu-cli` from now on to avoid the confusion.
