### ISSUE TITLE
Issue by using LEFT JOIN - unclear what is going wrong

### ISSUE THREAD

**Issue by JvD007** [kamu-data/kamu-cli#41]
I try to get this working but no luck. I'm doing something wrong with the LEFT JOIN. Unclear what is wrong.
[Enexis.zip](https://github.com/kamu-data/kamu-cli/files/6379473/Enexis.zip)

        SELECT
             cbs.`event_time`,
             2021.`event_time`,
             cbs.`gemeentenaam`,
             cbs.`provincienaam`,
             2021.`provincie`
             
        FROM

            `cbs.gemeenten.alfabetisch.2021` as cbs
            LEFT JOIN `decentrale.opwek.kleinverbruik.2021.01` as 2021 
            ON cbs.`provincienaam` = 2021.`provincie`
            ORDER BY cbs.`gemeentenaam`

Message:
$ **kamu-cli pull dummy**
  [1/1] Failed to update derivative dataset (dummy)
1 dataset(s) had errors

Summary of errors:

dummy: Transform error: Engine error: Contract error: Engine did not write a response file, see log files for details: /home/jaco/DataProjects/Energy/Enexis/.kamu/run/flink-submit-NeIeZB8sPp.out.txt /home/jaco/DataProjects/Energy/Enexis/.kamu/run/flink-submit-NeIeZB8sPp.err.txt /home/jaco/DataProjects/Energy/Enexis/.kamu/run/flink-taskmanager-NeIeZB8sPp.out.txt /home/jaco/DataProjects/Energy/Enexis/.kamu/run/flink-taskmanager-NeIeZB8sPp.err.txt /home/jaco/DataProjects/Energy/Enexis/.kamu/run/flink-jobmanager-NeIeZB8sPp.out.txt /home/jaco/DataProjects/Energy/Enexis/.kamu/run/flink-jobmanager-NeIeZB8sPp.err.txt

**Comment by sergiimk** [comment]
You should be able to see the error in `flink-submit-*.err.txt`:
```
SQL parse failed. Encountered "2021" at line 11, column 59.
```
On this line you are aliasing the table with `as` but provide `2021` as the name which is an invalid identifier in SQL:
```
LEFT JOIN `decentrale.opwek.kleinverbruik.2021.01` as 2021
``` 
Sorry again for the poor error reporting - it's at the top of our backlog, so will improve soon.


If I understand correctly what you're trying to achieve I recommend you:
* To first take a look at [this group of datasets](https://github.com/kamu-data/kamu-repo-contrib/tree/master/ca.vancouver.opendata/property/tax-report) as an example of combining several root datasets covering different points in time into one derivative dataset containing the history of changes - this would allow you combine your `decentrale.opwek.kleinverbruik.*` datasets into one.
* Then take a look at the [temporal table join example](https://github.com/kamu-data/kamu-cli/blob/master/docs/examples/trading.md) as looks like you will be joining historical records in the `cbs.gemeenten.alfabetisch.2021` dataset to values in `decentrale.opwek.kleinverbruik` **at certain points in time** (remember that kamu datasets are all histories of events).

The way you expressed the JOIN above is suitable for batch processing (so it would work in SQL shell and in notebooks), but derivative datasets are intended to be able to update as their dependencies get more data, so they require streaming-style joins (temporal table, or stream-to-stream).

Please re-open if you need further help.
