### ISSUE TITLE
 strange error:  IO error: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by JvD007** [kamu-data/kamu-cli#43]
This message appears if no datasets have been created in your workspace

**_$~/DataProjects/Share$ kamu sql
Error: IO error: No such file or directory (os error 2)_**

Is it possible to create a user friendly message :-) 

IO error is not so friendly

**Comment by sergiimk** [comment]
Fixed in `v0.40.1`. Thanks a lot for reporting.
