### ISSUE TITLE
Strange Change Date in LICENSE.txt

### ISSUE THREAD

**Issue by s373r** [kamu-data/kamu-cli#436]
### Describe the bug

Looks like we have wrong calculation for this field

LICENSE.txt:
```
...
Change Date:               2028-01-09
...
```

**Comment by sergiimk** [comment]
Wrong in what way?
Change date defines when our BSL license auto-converts into Apache 2.0 and should be lagging 4 years after each release.
See [licensing terms](https://docs.kamu.dev/contrib/license/)

**Comment by s373r** [comment]
@sergiimk Ah, I see, my bad -- I mistakenly thought it was an autogeneration error
