### ISSUE TITLE
Make dataset names and aliases comparisons case-insensitive

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-cli#469]
## Problem
- ODF restricts dataset name format to the grammar of domain names for compatibility with mechanisms like HTTP gateways and IPNS when dataset name appears in a subdomain. Subdomains are matched as case-insensitive.
- We likely don't want to allow datasets `fooBar` and `FooBar` and users `alice` and `alIce` to exist in our system due to risk of impersonation
- Finally the newly-introduced `DatasetRefPattern` also matches aliases as case-insensitive

## Proposal
- Spell out how case (in)sensitivity works in ODF spec
- Equality checks of `DatasetName` and `AccountName` should be made case-insensitive
- `DatasetRepository` implementations should be updated to case-insensitive comparisons when detecting name collisions
- Along the way we should revisit how equality is implemented for composite types like `DatasetRef`, e.g. cases like `DatasetRef::Alias("alice/foo") == DatasetRef::Handle("did:odf:abc", "alice/fool")`

**Comment by khh7** [comment]
Hi! I'm looking for a good first issue to work on and thought this would be an interesting one. Can I work on this if possible?

**Comment by sergiimk** [comment]
Hi @khh7, thanks for considering to contribute!

This issue should be a good one to start with and we'll be happy to guide you through the process.

You can start with `DEVELOPER.md` to set up your development environment and get the tests running locally.

Once you've done that and ready to start on the issue - please assign it to yourself, so that no one else picks it up simultaneously.

Feel free to reach out on Discord if you need help.
