### ISSUE TITLE
Installation on Windows directory error

### ISSUE THREAD

**Issue by JvD007** [kamu-data/kamu-cli#47]
Errors on Windows 10 by deploying the docker images:

kamu-cli-x86_64-pc-windows-msvc\kamu-cli-x86_64-pc-windows-msvc>kamu init --pull-images

Pulling image: kamudata/engine-spark:0.10.1
0.10.1: Pulling from kamudata/engine-spark
Digest: sha256:2765ff70b797ce336ffcc51a81b9dffc7cac33252a91bcc3ba3d960d9c2ae94b
Status: Image is up to date for kamudata/engine-spark:0.10.1
docker.io/kamudata/engine-spark:0.10.1
Pulling image: kamudata/engine-flink:0.7.0
0.7.0: Pulling from kamudata/engine-flink
6c33745f49b4: Pull complete
ef072fc32a84: Pull complete
c0afb8e68e0b: Pull complete
ed3e99843d3b: Pull complete
ebb7eeb2d7da: Pull complete
8832bda5b3e9: Pull complete
09c53b1a7aaf: Pull complete
e6124a2ca50e: Pull complete
d100a786aaa8: Pull complete
67eae1c8244d: Pull complete
a9bdf4b25d22: Extracting [==================================================>]    311MB/311MB
6be4223f2853: Download complete
d2df60f9bb00: Download complete
a1cb62377140: Download complete
e5d69c249d65: Download complete
3ba34aae1e9d: Download complete
failed to register layer**_: open /var/lib/docker/image/overlay2/layerdb/tmp/write-set-334267312/diff: read-only file system_**
Pulling image: kamudata/jupyter-uber:0.0.1
Error response from daemon: error creating temporary lease: write /var/lib/desktop-containerd/daemon/io.containerd.metadata.v1.bolt/meta.db: **_read-only file system: unknown_**

**Comment by sergiimk** [comment]
Hi @JvD007,

When you run `kamu init --pull-images` the tool simply executes a series of `docker pull ...` commands, so it's likely that there is something wrong with your environment.

Try running `docker pull kamudata/engine-flink:0.7.0` and see if it produces the same error.

From a quick search `"read-only file system"` is a very misleading error that Docker returns under many circumstances. The most common one - is when your [drive is out of space](https://forums.docker.com/t/error-read-only-file-system-write-var-lib-docker-buildkit-metadata-v2-db/103637).
