### ISSUE TITLE
Add login/password auth provider

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-cli#566]
~~Currently dummy auth expects password to match the account name, but in some very basic auth cases we would like to be able to customize the password.~~

- Replace dummy provider with login+password provider that stores salted/hashed passwords in the database
- Allow defining these accounts as predefined in the config (as a hash?)
- `kamu` account will become one such predefined account in our public envs where we specify its password in the config and set `isAdmin: true` flag

**Comment by zaychenko-sergei** [comment]
Motivation?

**Comment by sergiimk** [comment]
@zaychenko-sergei we currently don't have "Organization" accounts like in GitHub, so when we want to set up an account for a company and give multiple people admin access to some datasets we don't have a good option but to use password-based auth.

I see it as just a step from transforming our "dummy" auth into a standalone auth provider.

**Comment by zaychenko-sergei** [comment]
I think we should do normal database-backed implementation then.

**Comment by sergiimk** [comment]
If we can get to db-backed auth within 2-3 weeks I think that's acceptable.
