### ISSUE TITLE
Duplicate list subcommand in kamu help

### ISSUE THREAD

**Issue by davidgasquez** [kamu-data/kamu-cli#72]
Hey there! Running `kamu repo` seems to return a duplicate `list` subcommand in the help docs.
![1654168150](https://user-images.githubusercontent.com/1682202/171616834-7c5d859b-d134-48b7-9d60-5d9baa632b49.png)

**Comment by sergiimk** [comment]
Fixed in release `0.90.0`, thanks for reporting
