### ISSUE TITLE
`kamu version`: Vergen generation failure for `Linux / amd64 / musl`

### ISSUE THREAD

**Issue by s373r** [kamu-data/kamu-cli#789]
### Describe the bug

This regression was noticed in https://github.com/kamu-data/kamu-cli/actions/runs/10505067423/job/29102733887

According to a quick analysis, the default values are set in case of an error (based on https://github.com/rustyhorde/vergen/issues/216#issuecomment-1587418024)

### Steps To Reproduce

https://github.com/kamu-data/kamu-cli/actions/runs/10505067423/job/29102733887

### Current Behavior

```json
{
  "appVersion": "0.197.0",
  "buildTimestamp": "2024-08-22T08:40:44.340464232Z",
  "gitDescribe": "3009ff0",
  "gitSha": "3009ff0ad832ad7f0982da25043bb0d8e9539d4a",
  "gitCommitDate": "2024-08-22",
  "gitBranch": "HEAD",
  "rustcSemver": "1.81.0-nightly",
  "rustcChannel": "nightly",
  "rustcHostTriple": "x86_64-unknown-linux-gnu",
  "rustcCommitSha": "8337ba9189de188e2ed417018af2bf17a57d51ac",
  "cargoTargetTriple": "VERGEN_IDEMPOTENT_OUTPUT",
  "cargoFeatures": "VERGEN_IDEMPOTENT_OUTPUT",
  "cargoOptLevel": "VERGEN_IDEMPOTENT_OUTPUT"
}
```

### Expected Behavior

```json
{
  ...
  "cargoTargetTriple": "<INSERTED VALUE>",
  "cargoFeatures": "<INSERTED VALUE>",
  "cargoOptLevel": "<INSERTED VALUE>"
}
```

### kamu system info

```sh
-
```

### Anything else?

The previous release (`0.196.0`) works fine (https://github.com/kamu-data/kamu-cli/actions/runs/10452413434/job/28940778741)

**Comment by sergiimk** [comment]
Let's re-enable `fail_on_error` behavior in vergen so that we don't produce invalid builds

**Comment by s373r** [comment]
For the record: there was no error in the last build: https://github.com/kamu-data/kamu-cli/actions/runs/10580660385
