### ISSUE TITLE
Missing gpg keys for maven builds

### ISSUE THREAD

**Issue by LinuxUser404** [kamu-data/kamu-cli#8]
We need a way to use our versions of maven packages. That is a way to sing and distribute the fixed versions of packages we depend on.

**Comment by sergiimk** [comment]
Are you talking about signing of `hive` packages here or of `kamu` assembly? Not sure what you mean by "missing".

**Comment by LinuxUser404** [comment]
Signing of hive packages. Well it should not be limited to hive, since one day we might need to ship our versions of some dependencies, thus there should be a key we sign them with.

**Comment by sergiimk** [comment]
Created internal task for signing the assembly. 

For local development I think it's ok for developers to use personal gpg key to sign `hive`. Generating a key locally is less work than distributing one.
