### ISSUE TITLE
E2E: add coverage for Flow and Task system

### ISSUE THREAD

**Issue by zaychenko-sergei** [kamu-data/kamu-cli#817]
The test(s) should cover:
- [x] Creating root & derived datasets (using predefined files)
- [x] Defining flow configurations for updates and observing the triggers 
- [x] Triggering flows manually
- [x] Compacting & resetting flows

Currently, our E2E testing is based on low-level exchange of messages via GraphQL API.
Try prototyping higher level test steps that setup the fixture, apply actions and observe results from user point of view.

**Comment by s373r** [comment]
Within https://github.com/kamu-data/kamu-cli/pull/863, several E2E tests have been added that cover part of the expectations of this ticket:
- Creating root & derived datasets (using predefined files)
- Triggering flows manually

**Comment by s373r** [comment]
Task accomplished
