### ISSUE TITLE
Change input dataset for derived datasets when manual update fails

### ISSUE THREAD

**Issue by dmitriy-borzenko** [kamu-data/kamu-cli#820]
Current behaviour:

![image](https://github.com/user-attachments/assets/78539fc9-aab5-4534-8997-c45175419d42)

Expected behaviour:
Name of root dataset

**Comment by zaychenko-sergei** [comment]
To be released simultatenously with 
https://github.com/kamu-data/kamu-web-ui/commit/ac5b6782f805428d4a147809f8ffe8d5ec34c07e
