### ISSUE TITLE
API server: provide feature flags for UI

### ISSUE THREAD

**Issue by s373r** [kamu-data/kamu-cli#868]
By analyzing the task https://github.com/kamu-data/kamu-web-ui/issues/448, the need to add `/assets/runtime-config.json` was found out (see more in comment https://github.com/kamu-data/kamu-web-ui/issues/448#issuecomment-2383553990).

This can be done similarly to `WebUIServer`, which contains `WebUIFeatureFlags`.

**Comment by zaychenko-sergei** [comment]
It cannot be done similarly, as CLI server does not serve the web too, unlike `kamu ui` mode.
Instead I'm splitting the runtime configuration into 2 parts: as current, and with additinal HTTP query to the server.
