### ISSUE TITLE
Datafusion: cannot access a table in SQL if its name contains `-`

### ISSUE THREAD

**Issue by s373r** [kamu-data/kamu-cli#892]
### Describe the bug

Datafusion: cannot access a table in SQL if its name contains `-`

### Steps To Reproduce

1. Init a workspace
```shell
kamu init
```
2. Add a dataset with `-` in name (`player-scores` in our case)
```shell
kamu add https://raw.githubusercontent.com/kamu-data/kamu-cli/refs/heads/master/examples/leaderboard/player-scores.yaml
```
3. Make a query from this dataset 
```shell
kamu sql --command 'SELECT * FROM player-scores;'
```

### Current Behavior

```
Error:
  0: DataFusion error
  1: SQL error: ParserError("Expected end of statement, found: -")
  2: sql parser error: Expected end of statement, found: -
```

### Expected Behavior

No errors

### kamu system info

```sh
build:
  appVersion: 0.204.5
...
```

### Anything else?

Please update the `test_sql_command()` test after the fix.

Workaround: overwrite the name when adding

```shell
kamu init
kamu add https://raw.githubusercontent.com/kamu-data/kamu-cli/refs/heads/master/examples/leaderboard/player-scores.yaml --name scores
kamu sql --command 'SELECT * FROM scores;'
```
Output:
```
┌┐
││
├┤
││
└┘
```

**Comment by zaychenko-sergei** [comment]
This identifier is not a valid SQL, there is no issue with the report.

**Comment by s373r** [comment]
> This identifier is not a valid SQL, there is no issue with the report.

you're right, I was rushed

> and if it works let's close the ticket.

yes, it works

--

I'm closing the ticket because there's no bug
