### ISSUE TITLE
Create a new endpoint for REST API to read file from the uploaded token

### ISSUE THREAD

**Issue by dmitriy-borzenko** [kamu-data/kamu-cli#913]
You need to create a new endpoint that can download a file using the specified token.
At the input, the API accepts a token and returns the previously downloaded file
Example:
`GET http://localhost:8080//platform/file/upload/:upload_token`

**Comment by zaychenko-sergei** [comment]
Additional requirement: an ability to download uploaded file without authorization (anonymously).
The uploads should still be gated.
