### ISSUE TITLE
API for account flow list does not work correctly

### ISSUE THREAD

**Issue by dmitriy-borzenko** [kamu-data/kamu-cli#987]
Current behaviour:

1. Run the image with the command
`docker run -it --rm -p 8080:8080 -e KAMU_AUTH_GITHUB_CLIENT_ID=361a3b4fda86d0234d2f -e KAMU_AUTH_GITHUB_CLIENT_SECRET=465849325236ed49253993744069e1bec6808554 -e DATASET_ENV_VAR_ENCRYPTION_KEY=QfnEDcnUtGSW2pwVXaFPvZOwxyFm2BOC ghcr.io/kamu-data/kamu-base:latest-with-dataset-env-var-storage kamu system api-server --address 0.0.0.0 --http-port 8080 --external-address 127.0.0.1`
2. Login as admin
3. For any dataset, run a random flow for execution
4. Go to menu item "Your profile" and select "Flows" tab
5. Result

![image](https://github.com/user-attachments/assets/c827c71f-1f35-412a-b643-38073f8c96f7)
![image](https://github.com/user-attachments/assets/8c1f9a95-0d51-4b01-8416-b4ea3e207186)
![image](https://github.com/user-attachments/assets/ab3ccfae-6549-4cb1-a685-b1659da50d99)

Expected:
Should be a table with 1 running flow

**Comment by rmn-boiko** [comment]
Not reproducible with latest changes https://github.com/kamu-data/kamu-cli/pull/982
